<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <RootNamespace>Efiron.App</RootNamespace>
    <AssemblyName>Efiron</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PlatformTarget>x64</PlatformTarget>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <AppxPackage>false</AppxPackage>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinUI" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Efiron.Core\Efiron.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PRIResource Include="Strings\**\*.resw" />
  </ItemGroup>
</Project>
