<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Efiron.Application</RootNamespace>
    <AssemblyName>Efiron.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Efiron.Domain\Efiron.Domain.csproj" />
  </ItemGroup>
</Project>
