namespace Efiron.Domain.Playback;

public sealed record PlaybackBackendCapabilities(
    bool ContainerMetadata,
    bool CodecMetadata,
    bool FrameStatistics,
    bool InputBitrate,
    bool Buffering,
    bool HardwareDecodingStatus,
    bool RendererMetadata,
    bool AudioTracks,
    bool SubtitleTracks,
    bool MediaPosition);

public sealed record PlaybackBackendDiagnostics(
    DateTimeOffset SampledAtUtc,
    PlaybackBackendId BackendId,
    string? BackendVersion,
    string SelectedProfile,
    PlaybackBackendCapabilities Capabilities,
    string? StreamUrlScheme,
    string? Container,
    string? VideoCodec,
    string? AudioCodec,
    int? VideoWidth,
    int? VideoHeight,
    double? DeclaredFramesPerSecond,
    double? RenderedFramesPerSecond,
    long? DisplayedFrames,
    long? DroppedFrames,
    double? InputBitrateBitsPerSecond,
    TimeSpan? BufferDuration,
    double? BufferedPercentage,
    long? BufferUnderruns,
    long? RebufferCount,
    long? Discontinuities,
    bool? HardwareDecodingRequested,
    bool? HardwareDecodingActive,
    string? Decoder,
    string? GraphicsDevice,
    string? VideoRenderer,
    TimeSpan? AudioVideoDrift,
    TimeSpan? StartupLatency,
    TimeSpan? TimeToFirstFrame,
    PlaybackState PlaybackState,
    string? PlaybackError,
    TimeSpan? SessionDuration,
    TimeSpan? MediaPosition,
    string? AudioTrack,
    string? SubtitleTrack,
    double? DisplayFramesPerSecond = null,
    double? EstimatedDisplayFramesPerSecond = null,
    double? VideoSpeedCorrection = null,
    double? AudioSpeedCorrection = null,
    double? VSyncRatio = null,
    long? MistimedFrames = null,
    long? DelayedFrames = null,
    string? PixelFormat = null,
    string? PresentationMode = null,
    bool? InterpolationActive = null)
{
    public static PlaybackBackendDiagnostics Unsupported(
        PlaybackBackendId backendId,
        string? backendVersion,
        string selectedProfile,
        PlaybackBackendCapabilities capabilities,
        PlaybackSnapshot snapshot,
        TimeSpan? sessionDuration = null,
        TimeSpan? mediaPosition = null,
        bool? hardwareDecodingRequested = null) =>
        new(
            DateTimeOffset.UtcNow,
            backendId,
            backendVersion,
            selectedProfile,
            capabilities,
            snapshot.Source?.Scheme,
            Container: null,
            VideoCodec: null,
            AudioCodec: null,
            VideoWidth: null,
            VideoHeight: null,
            DeclaredFramesPerSecond: null,
            RenderedFramesPerSecond: null,
            DisplayedFrames: null,
            DroppedFrames: null,
            InputBitrateBitsPerSecond: null,
            BufferDuration: null,
            BufferedPercentage: null,
            BufferUnderruns: null,
            RebufferCount: null,
            Discontinuities: null,
            HardwareDecodingRequested: hardwareDecodingRequested,
            HardwareDecodingActive: null,
            Decoder: null,
            GraphicsDevice: null,
            VideoRenderer: null,
            AudioVideoDrift: null,
            StartupLatency: null,
            TimeToFirstFrame: null,
            snapshot.State,
            snapshot.ErrorMessage,
            sessionDuration,
            mediaPosition,
            AudioTrack: null,
            SubtitleTrack: null);
}
